# Generated by Django 4.0.3 on 2022-05-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=25)),
                ('userName', models.CharField(max_length=25)),
                ('userFriend', models.CharField(max_length=25)),
                ('userFriendId', models.CharField(max_length=25)),
            ],
        ),
    ]
