# Generated by Django 4.0.3 on 2022-05-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_friend'),
    ]

    operations = [
        migrations.CreateModel(
            name='PillList',
            fields=[
                ('ModuleNum', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('PillMaster', models.CharField(max_length=45)),
                ('PillName', models.CharField(max_length=45)),
                ('PillAmount', models.CharField(max_length=45)),
                ('PillDay', models.CharField(max_length=45)),
                ('PillTime', models.CharField(max_length=45)),
                ('PillEat', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='PillTake',
            fields=[
                ('ModuleNum', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('PillTakeTime', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='PillTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ModuleNum', models.CharField(max_length=45)),
                ('PillName', models.CharField(max_length=45)),
                ('PillMaster', models.CharField(max_length=45)),
                ('EatTime', models.CharField(max_length=45)),
            ],
        ),
    ]
