# Generated by Django 4.0.3 on 2022-05-27 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0003_pilllist_pilltake_pilltime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pilllist',
            name='PillDay',
        ),
    ]
